// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bcycle_backend.Data;

namespace bcycle_backend.Migrations
{
    [DbContext(typeof(BCycleContext))]
    partial class BCycleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("bcycle_backend.Models.GroupTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("HostId");

                    b.Property<string>("MapImageUrl");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("TripCode");

                    b.HasKey("Id");

                    b.ToTable("GroupTrip");
                });

            modelBuilder.Entity("bcycle_backend.Models.GroupTripParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupTripId");

                    b.Property<bool>("IsApproved");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GroupTripId");

                    b.ToTable("GroupTripParticipant");
                });

            modelBuilder.Entity("bcycle_backend.Models.GroupTripPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupTripId");

                    b.Property<float>("Latitude");

                    b.Property<float>("Longitude");

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.HasIndex("GroupTripId");

                    b.ToTable("GroupTripPoint");
                });

            modelBuilder.Entity("bcycle_backend.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Distance");

                    b.Property<DateTime>("Finished");

                    b.Property<int?>("GroupTripId");

                    b.Property<string>("MapImageUrl");

                    b.Property<DateTime>("Started");

                    b.Property<int>("Time");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GroupTripId");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("bcycle_backend.Models.TripPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PhotoUrl");

                    b.Property<int>("TripId");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripPhoto");
                });

            modelBuilder.Entity("bcycle_backend.Models.TripPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Latitude");

                    b.Property<float>("Longitude");

                    b.Property<DateTime>("TimeReached");

                    b.Property<int>("TripId");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripPoint");
                });

            modelBuilder.Entity("bcycle_backend.Models.GroupTripParticipant", b =>
                {
                    b.HasOne("bcycle_backend.Models.GroupTrip", "GroupTrip")
                        .WithMany("Participants")
                        .HasForeignKey("GroupTripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bcycle_backend.Models.GroupTripPoint", b =>
                {
                    b.HasOne("bcycle_backend.Models.GroupTrip", "GroupTrip")
                        .WithMany("GroupTripPoints")
                        .HasForeignKey("GroupTripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bcycle_backend.Models.Trip", b =>
                {
                    b.HasOne("bcycle_backend.Models.GroupTrip", "GroupTrip")
                        .WithMany()
                        .HasForeignKey("GroupTripId");
                });

            modelBuilder.Entity("bcycle_backend.Models.TripPhoto", b =>
                {
                    b.HasOne("bcycle_backend.Models.Trip", "Trip")
                        .WithMany("TripPhotos")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bcycle_backend.Models.TripPoint", b =>
                {
                    b.HasOne("bcycle_backend.Models.Trip", "Trip")
                        .WithMany("TripPoints")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
